version: "3.7"
services: 
  postgres:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'

  api:
    build: ./api
    volumes: 
      - ./api:/opt/app
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      PORT: 3002
    ports: 
      - '3002:3002'
    depends_on: 
      - postgres

    